# Generated by Django 6.0.1 on 2026-05-04 01:43

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _legacy_usd_to_vnd_books(apps, schema_editor):
    """
    Một lần: giá cũ trong DB là USD (số nhỏ) -> nhân 25000 thành VNĐ.
    Bản ghi đã là VNĐ (thường > 5000) thì giữ nguyên.
    """
    Book = apps.get_model('bookstore_app', 'Book')
    rate = Decimal('25000')
    threshold = Decimal('5000')
    for b in Book.objects.iterator():
        p = b.price
        if p is None:
            continue
        if p > threshold:
            continue
        new_price = (p * rate).quantize(Decimal('1'))
        new_discount = None
        if b.discount_price is not None:
            if b.discount_price <= threshold:
                new_discount = (b.discount_price * rate).quantize(Decimal('1'))
            else:
                new_discount = b.discount_price.quantize(Decimal('1'))
        Book.objects.filter(pk=b.pk).update(price=new_price, discount_price=new_discount)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_legacy_usd_to_vnd_books, _noop_reverse),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore_app.author', verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore_app.category', verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='books/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_books', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Mô tả đầy đủ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Để trống nếu không giảm giá.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khuyến mãi (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị trên cửa hàng'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Sách nổi bật'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='Tiếng Việt', max_length=50, verbose_name='Ngôn ngữ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số trang'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Số tiền Việt Nam Đồng, không quy đổi.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá bìa (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(verbose_name='Ngày xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore_app.publisher', verbose_name='Nhà xuất bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm trung bình'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reviews_count',
            field=models.IntegerField(default=0, verbose_name='Số lượt đánh giá'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Còn hàng'), ('low_stock', 'Sắp hết hàng'), ('out_of_stock', 'Hết hàng'), ('discontinued', 'Ngừng bán')], default='available', max_length=20, verbose_name='Trạng thái kho'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
    ]
